#ifndef _foreach_h
#define _foreach_h

#include <stdbool.h>


#define foreach(VARIABLE_TYPE, VARIABLE_NAME, ITERATOR, INSTANCE) ITERATOR(INSTANCE, VARIABLE_TYPE, VARIABLE_NAME)

#define foreach__2(VARIABLE_TYPE, VARIABLE_NAME, INSTANCE, ITERATOR_TYPE, ENUMERATOR, ITERATOR, POINTER_CAST)                               \
    for (ITERATOR_TYPE iterator##__##VARIABLE_NAME = ENUMERATOR(INSTANCE); iterator##__##VARIABLE_NAME.__run; iterator##__##VARIABLE_NAME.__run = false) \
        for (VARIABLE_TYPE VARIABLE_NAME; ITERATOR(&iterator##__##VARIABLE_NAME, POINTER_CAST&VARIABLE_NAME);)

#define foreach__3(VARIABLE_TYPE, VARIABLE_NAME, INSTANCE, ITERATOR_TYPE, ENUMERATOR, ITERATOR, ITERATOR_DESTROY, POINTER_CAST) \
    for (ITERATOR_TYPE iterator##__##VARIABLE_NAME = ENUMERATOR(INSTANCE); iterator##__##VARIABLE_NAME.__run; ITERATOR_DESTROY)     \
        for (VARIABLE_TYPE VARIABLE_NAME; ITERATOR(&iterator##__##VARIABLE_NAME, POINTER_CAST&VARIABLE_NAME);)

#endif
