#ifndef _gamepad_types_h
#define _gamepad_types_h

typedef enum {
    GAMEPAD_A = 1 << 0,
    GAMEPAD_B = 1 << 1,
    GAMEPAD_X = 1 << 2,
    GAMEPAD_Y = 1 << 3,

    GAMEPAD_DPAD_UP = 1 << 4,
    GAMEPAD_DPAD_DOWN = 1 << 5,
    GAMEPAD_DPAD_RIGHT = 1 << 6,
    GAMEPAD_DPAD_LEFT = 1 << 7,

    GAMEPAD_START = 1 << 8,
    GAMEPAD_SELECT = 1 << 9,

    GAMEPAD_TRIGGER_LEFT = 1 << 10,
    GAMEPAD_TRIGGER_RIGHT = 1 << 11,
    GAMEPAD_BUMPER_LEFT = 1 << 12,
    GAMEPAD_BUMPER_RIGHT = 1 << 13,

    GAMEPAD_APAD_UP = 1 << 14,
    GAMEPAD_APAD_DOWN = 1 << 15,
    GAMEPAD_APAD_RIGHT = 1 << 16,
    GAMEPAD_APAD_LEFT = 1 << 17,

    GAMEPAD_DPAD2_UP = 1 << 18,
    GAMEPAD_DPAD2_DOWN = 1 << 19,
    GAMEPAD_DPAD2_RIGHT = 1 << 20,
    GAMEPAD_DPAD2_LEFT = 1 << 21,

    GAMEPAD_DPAD3_UP = 1 << 22,
    GAMEPAD_DPAD3_DOWN = 1 << 23,
    GAMEPAD_DPAD3_RIGHT = 1 << 24,
    GAMEPAD_DPAD3_LEFT = 1 << 25,

    GAMEPAD_DPAD4_UP = 1 << 26,
    GAMEPAD_DPAD4_DOWN = 1 << 27,
    GAMEPAD_DPAD4_RIGHT = 1 << 28,
    GAMEPAD_DPAD4_LEFT = 1 << 29,

    GAMEPAD_BACK = 1 << 30,


    // combinations
    GAMEPAD_AD_UP = GAMEPAD_DPAD_UP | GAMEPAD_APAD_UP,
    GAMEPAD_AD_DOWN = GAMEPAD_DPAD_DOWN | GAMEPAD_APAD_DOWN,
    GAMEPAD_AD_RIGHT = GAMEPAD_DPAD_RIGHT | GAMEPAD_APAD_RIGHT,
    GAMEPAD_AD_LEFT = GAMEPAD_DPAD_LEFT | GAMEPAD_APAD_LEFT,
    GAMEPAD_AD = GAMEPAD_AD_DOWN | GAMEPAD_AD_UP | GAMEPAD_AD_LEFT | GAMEPAD_AD_RIGHT,
    GAMEPAD_T_LR = GAMEPAD_TRIGGER_LEFT | GAMEPAD_TRIGGER_RIGHT,
    GAMEPAD_B_LR = GAMEPAD_BUMPER_LEFT | GAMEPAD_BUMPER_RIGHT,
    GAMEPAD_DALL_UP = GAMEPAD_DPAD_UP | GAMEPAD_DPAD2_UP | GAMEPAD_DPAD3_UP | GAMEPAD_DPAD4_UP,
    GAMEPAD_DALL_DOWN = GAMEPAD_DPAD_DOWN | GAMEPAD_DPAD2_DOWN | GAMEPAD_DPAD3_DOWN | GAMEPAD_DPAD4_DOWN,
    GAMEPAD_DALL_RIGHT = GAMEPAD_DPAD_RIGHT | GAMEPAD_DPAD2_RIGHT | GAMEPAD_DPAD3_RIGHT | GAMEPAD_DPAD4_RIGHT,
    GAMEPAD_DALL_LEFT = GAMEPAD_DPAD_LEFT | GAMEPAD_DPAD2_LEFT | GAMEPAD_DPAD3_LEFT | GAMEPAD_DPAD4_LEFT,

} GamepadButtons;

typedef struct Gamepad_s* Gamepad;

#endif
