internal delegate void glGetIntegerv(GLenum pname, GLint* data);
internal delegate void glLoadIdentity(void);
internal delegate void glMatrixMode(GLenum mode);
internal delegate void gluOrtho2D(GLdouble left, GLdouble right, GLdouble top, GLdouble bottom);
internal delegate void glViewport(GLintx,GLinty,GLsizei width,GLsizei height);
internal delegate void glHint(GLenum target, GLenum mode);
internal delegate void glDepthFunc(GLenum func);
internal delegate void glClearDepth(GLclampd depth);
internal delegate void glShadeModel(GLenum mode);
internal delegate void glFlush(void);
internal delegate GLenum glGetError(void);
internal delegate void glBindTexture(GLenum target, GLuint texture);
internal delegate void glUseProgram(GLuint program);
internal delegate void glDeleteProgram(GLuint program);
internal delegate GLuint glCreateProgram(void);
internal delegate void glActiveTexture(GLenum texture);
internal delegate void glBindBuffer(GLenum target, GLuint buffer);
internal delegate void glEnableVertexAttribArray(GLuint index);
internal delegate void glGetProgramiv(GLuint program, GLenum pname, GLint *params);
internal delegate void glGetProgramInfoLog(GLuint program, GLsizei maxLength, GLsizei *length, GLchar *infoLog);
internal delegate void glAttachShader(GLuint program, GLuint shader);
internal delegate void glLinkProgram(GLuint program);
internal delegate void glGetShaderiv(GLuint shader, GLenum pname, GLint *params);
internal delegate void glDeleteShader(GLuint shader);
internal delegate void glGetShaderInfoLog(GLuint shader, GLsizei maxLength, GLsizei *length, GLchar *infoLog);
internal delegate void glCompileShader(GLuint shader);
internal delegate void glShaderSource(GLuint shader, GLsizei count, const GLchar **string, const GLint *length);
internal delegate GLuint glCreateShader(GLenum shaderType);
internal delegate void glDrawArrays(GLenum mode, GLint first, GLsizei count);
internal delegate void glUniform4fv(GLint location, GLsizei count, const GLfloat *value);
internal delegate void glUniformMatrix4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
internal delegate void glVertexAttribPointer(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void * pointer);
internal delegate GLint glGetAttribLocation(GLuint program, const GLchar *name);
internal delegate GLint glGetUniformLocation(GLuint program, const GLchar *name);
internal delegate void glGenBuffers(GLsizei n, GLuint * buffers);
internal delegate void glUniform1i(GLint location, GLint v0);
internal delegate void glUniform1f(GLint location, GLfloat v0);
internal delegate void glClear(GLbitfield mask);
internal delegate void glClearColor(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
internal delegate void glTexParameteri(GLenum target, GLenum pname, GLint param);
internal delegate void glGenTextures(GLsizei n, GLuint * textures);
internal delegate void glGenerateMipmap(GLenum target);
internal delegate void glTexImage2D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void * data);
internal delegate void glPixelStorei(GLenum pname, GLint param);
internal delegate void glBlendFuncSeparate(GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
internal delegate void glBlendFunc(GLenum sfactor, GLenum dfactor);
internal delegate void glEnable(GLenum cap);
internal delegate void glDisable(GLenum cap);
internal delegate void glDepthMask(GLboolean flag);
internal delegate void glBufferData(GLenum target, GLsizeiptr size, const void * data, GLenum usage);
internal delegate void glDeleteTextures(GLsizei n, const GLuint * textures);
internal delegate void glVertexAttribDivisor(GLuint index, GLuint divisor);
internal delegate void glDrawElementsInstanced(GLenum mode, GLsizei count, GLenum type, const void * indices, GLsizei instancecount);
internal delegate void glViewport(GLint x, GLint y, GLsizei width, GLsizei height);
internal delegate void glDrawElements(GLenum mode, GLsizei count, GLenum type, IntPtr indices);