#ifndef __animlist_h
#define __animlist_h

#define ANIM_MACRO_INTERPOLATOR_EASE 0
#define ANIM_MACRO_INTERPOLATOR_EASE_IN 1
#define ANIM_MACRO_INTERPOLATOR_EASE_OUT 2
#define ANIM_MACRO_INTERPOLATOR_EASE_IN_OUT 3
#define ANIM_MACRO_INTERPOLATOR_LINEAR 4
#define ANIM_MACRO_INTERPOLATOR_STEPS 5

typedef unsigned char ANIM_INTERPOLATOR_TYPE;

#endif

